name: Replace version in k8s manifests on main tag push
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  replace_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Replace image version in k8s manifests
        run: |
          for file in k8s/*.yaml; do
             sed -i "s|ghcr.io/src-doo/netbox-ssot:v.*.*.*|ghcr.io/src-doo/netbox-ssot:${{ github.ref_name }}|g" "$file"
           done

      - name: Commit and push changes
        run: |
          git config --global user.name "src-csm"
          git config --global user.email "199741225+src-csm@users.noreply.github.com"
          git add .
          git commit -m "chore(k8s): Replace version in k8s manifests"
          git push -f
